# Generated by Django 4.2.1 on 2024-06-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.CharField(max_length=100, verbose_name='tg id')),
                ('tg_user_name', models.CharField(max_length=100, verbose_name='tg name')),
                ('count', models.CharField(max_length=100, verbose_name='count')),
                ('recover', models.CharField(max_length=100, verbose_name='recovery')),
                ('tab', models.CharField(max_length=100, verbose_name='profit per tab')),
                ('max_storage', models.CharField(max_length=100, verbose_name='max storage')),
                ('cliker', models.CharField(default=0, max_length=100, verbose_name='autocliker')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
