# Generated by Django 4.2.1 on 2024-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='recover_lvl',
            field=models.CharField(default='1', max_length=100, verbose_name='recover_lvl'),
        ),
        migrations.AddField(
            model_name='users',
            name='storage_lvl',
            field=models.CharField(default='1', max_length=100, verbose_name='storage_lvl'),
        ),
        migrations.AddField(
            model_name='users',
            name='tab_lvl',
            field=models.CharField(default='1', max_length=100, verbose_name='tab_lvl'),
        ),
    ]
