# Generated by Django 4.2.1 on 2024-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_users_recover_lvl_users_storage_lvl_users_tab_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='count',
            field=models.CharField(default=0, max_length=100, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='users',
            name='max_storage',
            field=models.CharField(default=1000, max_length=100, verbose_name='max storage'),
        ),
        migrations.AlterField(
            model_name='users',
            name='recover',
            field=models.CharField(default=1, max_length=100, verbose_name='recovery'),
        ),
        migrations.AlterField(
            model_name='users',
            name='recover_lvl',
            field=models.CharField(default=1, max_length=100, verbose_name='recover_lvl'),
        ),
        migrations.AlterField(
            model_name='users',
            name='storage_lvl',
            field=models.CharField(default=1, max_length=100, verbose_name='storage_lvl'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tab',
            field=models.CharField(default=1, max_length=100, verbose_name='profit per tab'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tab_lvl',
            field=models.CharField(default=1, max_length=100, verbose_name='tab_lvl'),
        ),
    ]
