# Generated by Django 4.2.1 on 2024-06-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_users_count_alter_users_max_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.CharField(default=0, max_length=100, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='users',
            name='referal_id',
            field=models.CharField(default='', max_length=100, verbose_name='ID пригласившего вас пользователя'),
        ),
        migrations.AddField(
            model_name='users',
            name='tg_user_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
