# Generated by Django 4.2.1 on 2024-06-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_users_balance_users_referal_id_users_tg_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='referal_id',
            field=models.CharField(default='-', max_length=100, verbose_name='ID пригласившего вас пользователя'),
        ),
    ]
