# Generated by Django 4.2.1 on 2024-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_users_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tg_user_img',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='images/'),
        ),
    ]
