# Generated by Django 4.2.1 on 2024-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_users_tg_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tg_user_img',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='media/images/'),
        ),
    ]
