# Generated by Django 4.2.1 on 2024-06-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_users_tg_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='storage',
            field=models.CharField(default=1000, max_length=100, verbose_name='Count of Storage'),
        ),
    ]
