# Generated by Django 4.2.1 on 2024-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_users_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rating',
            field=models.CharField(default='Bronze', max_length=100, verbose_name='Rating'),
        ),
    ]
