# Generated by Django 4.2.1 on 2024-06-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_users_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='aim',
            field=models.CharField(default=20000, max_length=1000, verbose_name='aim'),
        ),
    ]
