# Generated by Django 4.2.1 on 2024-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_users_aim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aim',
            field=models.CharField(default=100000, max_length=1000, verbose_name='aim'),
        ),
    ]
