# Generated by Django 4.2.1 on 2024-06-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_users_aim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='aim',
        ),
        migrations.AddField(
            model_name='users',
            name='point',
            field=models.CharField(default=100000, max_length=1000, verbose_name='point'),
        ),
    ]
