# Generated by Django 4.2.1 on 2024-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_remove_users_aim_users_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cliker_on',
            field=models.BooleanField(default=False),
        ),
    ]
