# Generated by Django 4.2.1 on 2024-06-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_users_cliker_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleateTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_id', models.CharField(max_length=100, verbose_name='user_id')),
                ('nubmerOfTask', models.CharField(max_length=100, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'CompleateTask',
                'verbose_name_plural': 'CompleatesTasks',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nubmerOfTask', models.CharField(max_length=100, verbose_name='Number')),
                ('description', models.CharField(max_length=100, verbose_name='descript')),
                ('reward', models.CharField(max_length=100, verbose_name='reward')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
