# Generated by Django 4.2.1 on 2024-06-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_tasks_field_tasks_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='compleatetasks',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='field',
            field=models.CharField(default=' - ', max_length=100, verbose_name='field from db'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='result',
            field=models.CharField(default='-', max_length=100, verbose_name='result'),
        ),
    ]
