# Generated by Django 4.2.1 on 2024-06-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_compleatetasks_date_alter_tasks_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compleatetasks',
            old_name='nubmerOfTask',
            new_name='numberOfTask',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='nubmerOfTask',
            new_name='numberOfTask',
        ),
    ]
