# Generated by Django 4.2.1 on 2024-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_rename_nubmeroftask_compleatetasks_numberoftask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compleatetasks',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
