# Generated by Django 4.2.1 on 2024-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_alter_compleatetasks_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cliker_box',
            field=models.CharField(default=0, max_length=100, verbose_name='collect'),
        ),
        migrations.AddField(
            model_name='users',
            name='cliker_box_max',
            field=models.CharField(default=0, max_length=100, verbose_name='max_collect'),
        ),
    ]
